// 异采 YiCai 供应商端 Supabase 配置
const SUPABASE_URL = 'https://spb-hifzhn3j7pqw971s.supabase.opentrust.net';
const SUPABASE_ANON_KEY = 'eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJyb2xlIjoiYW5vbiIsInJlZiI6InNwYi1oaWZ6aG4zajdwcXc5NzFzIiwiaXNzIjoic3VwYWJhc2UiLCJpYXQiOjE3ODUzMjUxODAsImV4cCI6MjEwMDkwMTE4MH0.odNQDfrqf2AmXKkEIrAfCSpkS6qNZ3GoADUD8IDWBDs';
